#!/bin/bash

for entry in "../log"/*
do
	while read line
	do
	var1=$(echo $line |cut -d':' -f4)
	if [ "$var1" = " search " ]; then
		var3=0
		var2=$(echo $line |cut -d':' -f5)
		if [[ " ${arr[*]} " != *" $var2 "* ]]; then
			arr=("$var2" "${arr[@]}")
		else
			
		fi
		IFS=':' read -r -a ADDR <<< "$line"
		for i in "${ADDR[@]}"; do
			var3=$((var3+1))
		done
		var3=$((var3-5))
		echo "$var3"
	fi
	done < "$entry"
done

echo "Keyword most frequently found: $x"  